apiVersion: v1
kind: Service
metadata:
  name: golang-service
  namespace: devops-course-backend
spec:
  type: NodePort
  selector:
    app: golang
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
