apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
  namespace: devops-course-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: anastasiiazakharchuk/devops-course-node
        name: devops-course-node
        envFrom:
          - configMapRef:
              name: configmap
