apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: devops-course-frontend
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
