global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files: [ ]

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: backend
    scrape_interval: 5s
    static_configs:
      - targets:
          - golang:8080

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets:
            - "alertmanager:9093"
