services:
  golang:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  redis:
    image: redis

